fm_calendar_event:
    pattern:  /
    defaults: { _controller: "FMCalendarBundle:Event:index" }
    
fm_calendar_event_list_author:
    pattern:  /par/{username}
    defaults: { _controller: "FMCalendarBundle:Event:listByUser" }

fm_calendar_event_new:
    pattern:  /nouveau
    defaults: { _controller: "FMCalendarBundle:Event:new" }

fm_calendar_event_create:
    pattern:  /creer
    defaults: { _controller: "FMCalendarBundle:Event:create" }
    requirements: { _method: post }

fm_calendar_event_edit:
    pattern:  /{id}/editer
    defaults: { _controller: "FMCalendarBundle:Event:edit" }

fm_calendar_event_update:
    pattern:  /{id}/mettreajour
    defaults: { _controller: "FMCalendarBundle:Event:update" }
    requirements: { _method: post }

fm_calendar_event_delete:
    pattern:  /{id}/supprimer
    defaults: { _controller: "FMCalendarBundle:Event:delete" }
    requirements: { _method: post }
