fm_calendar_event:
    pattern:  /
    defaults: { _controller: "FMCalendarBundle:Event:index" }
    requirements: { _method: get }
    
fm_calendar_event_list_author:
    pattern:  /par/{username}
    defaults: { _controller: "FMCalendarBundle:Event:listByUser" }
    requirements: { _method: get }

fm_calendar_event_new:
    pattern:  /nouveau
    defaults: { _controller: "FMCalendarBundle:Event:new" }
    requirements: { _method: get|post }


fm_calendar_event_edit:
    pattern:  /{id}/editer
    defaults: { _controller: "FMCalendarBundle:Event:edit" }
    requirements: { _method: get|post }

fm_calendar_event_delete:
    pattern:  /{id}/supprimer
    defaults: { _controller: "FMCalendarBundle:Event:delete" }
    requirements: { _method: post }
