FMCalendarBundle:
    resource: "@FMCalendarBundle/Resources/config/routing.yml"
    prefix:   /calendrier

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
