parameters:
#    fm_archer_agnetz.example.class: FM\ArcherAgnetzBundle\Example

services:
#    fm_archer_agnetz.example:
#        class: %fm_archer_agnetz.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
