fm_calendar_homepage:
    pattern:  /
    defaults: { _controller: FMCalendarBundle:Event:index }
    
fm_calendar_event:
    resource: "@FMCalendarBundle/Resources/config/routing/event.yml"
    prefix:   /evenement

fm_calendar_my_events:
    pattern:  /mes-evenements
    defaults: { _controller: FMCalendarBundle:Default:myEvents }
    requirements: { _method: get }