parameters:
#    fm_calendar.example.class: FM\CalendarBundle\Example

services:
#    fm_calendar.example:
#        class: %fm_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
