fm_user_invit:
    pattern:  /admin/invitation
    defaults: { _controller: 'FMUserBundle:Invitation:index' }
    requirements:
        _method:  GET

fm_user_invit_send:
    pattern:   /admin/invitation/send
    defaults: { _controller: 'FMUserBundle:Invitation:send' }
    requirements:
        _method:  POST

fm_user_invit_show:
    pattern:  /admin/invitation/{id}/show
    defaults: { _controller: 'FMUserBundle:Invitation:show' }
    requirements:
        _method: POST
        
fm_user_invit_delete:
    pattern:  /admin/invitation/{id}/delete
    defaults: { _controller: 'FMUserBundle:Invitation:delete' }
    requirements:
        _method: POST