services:
    fm_user.registration.form.type:
        class:  FM\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fm_user_registration }

    fm_user.profile.form.type:
        class:  FM\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fm_user_profile }

    fm_user.controller.invitation:
        class: FM\UserBundle\Controller\InvitationController
        scope: request
        arguments: ['@doctrine.orm.entity_manager', '@request', '@templating', '@router']