services:
    fm_archer_agnetz.navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            - { leftmenu: @fm_archer_agnetz.navbar_main_menu=, rightmenu: @fm_archer_agnetz.navbar_right_menu= }
            - {}
            - { title: "ASA Tir à l'arc", titleRoute: "fm_archer_agnetz_home", fixedTop: true, isFluid: false }
        tags:
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }

    fm_archer_agnetz.navbar_menu_builder:
        class: FM\ArcherAgnetzBundle\Menu\NavbarMenuBuilder
        scope: request
        arguments: [ '@knp_menu.factory', '@security.context' ]

    fm_archer_agnetz.navbar_main_menu:
        class: Knp\Menu\MenuItem
        factory_service: fm_archer_agnetz.navbar_menu_builder
        factory_method: createMainMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    fm_archer_agnetz.navbar_right_menu:
        class: Knp\Menu\MenuItem
        factory_service: fm_archer_agnetz.navbar_menu_builder
        factory_method: createRightSideDropdownMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }