<?php

namespace FM\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    private function getQueryAllByVisibility($visibility)
    {
       return $this->getEntityManager()
            ->createQuery('
                SELECT e, c FROM FMCalendarBundle:Event e
                JOIN e.calendar c
                WHERE c.visibility = :visibility
                ORDER BY e.dtstart DESC'
            )->setParameter('visibility', $visibility);
    }

    private function getQueryAllByAuthor(UserInterface $author)
    {
       return $this->getEntityManager()
            ->createQuery('
                SELECT e FROM FMCalendarBundle:Event e
                WHERE e.created_by = :author
                ORDER BY e.dtstart DESC'
            )->setParameter('author', $author);
    }

    public function findAllPublic()
    {
        try {
            return $this->getQueryAllByVisibility('public')->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findAllByAuthor(UserInterface $author)
    {
        try {
            return $this->getQueryAllByAuthor($author)->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
